spring: 
  datasource: 
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE 
    username: test 
    password: test 
    driverClassName: org.h2.Driver 
  jpa: 
    show-sql: true 
    properties: 
      hibernate: 
        ddl-auto: update 
        format_sql: true 
        dialect: org.hibernate.dialect.H2Dialect